name: Generate Sitemap

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install @supabase/supabase-js

      - run: node generate-sitemap.js
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

      - name: Commit sitemap
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add sitemap*.xml
          git commit -m "update sitemap"
          git push
